call_eval.py:111: RuntimeWarning: invalid value encountered in double_scalars
  
